### ISSUE TITLE
System does not find the GoDiceApp

### ISSUE THREAD

**Issue by Hijah82** [ParticulaCode/FoundryVTT-GoDice#10]
The System prompts some mistakes. The GoDice App was not find in FoundryVTT? FoundryVTT and Mobile Device with the App are in the same WLAN.
![Screenshot 2023-07-14 092606](https://github.com/foundryvtt/unfulfilled-rolls/assets/137417695/57600b86-afcb-4d22-96df-3dc1bffb6a6e)
![Screenshot (19)](https://github.com/foundryvtt/unfulfilled-rolls/assets/137417695/cf439d6e-0bd2-4490-abac-a54b3a74f116)

**Comment by 13GingeR** [comment]
i have the same problem :(
i tried phone and tablet but 'dice is not connetced. make sure app is running'

**Comment by AKparticula** [comment]
This issue relates to the wrong IP given by the app, an update to the app will be out in around 1 week.
for now can solve by disabling mobile data on your phone to make sure you get the same IP initials as your PC's IP
(Usually, an IP that starts with 192...)

**Comment by 13GingeR** [comment]
thx for info.  and  temporary solution works like a charm.  i Love GoDice :)

i hope for wide support for dices (dndBeyond / demiplane / more VTTs)

**Comment by Panda-Beard** [comment]
Hi! I'm also experiencing similar issues. However, when I changed over to my tablet and have a ws://192. IP, it is not working at all. The pop-up roll-prompt box comes up, can be dragged around, but will not close (unless I refresh the screen), and the rolling does nothing. It responds on the app, but not on the PC. This is really frustrating. Is there anything I can do?

**Comment by AKparticula** [comment]
> h

Hi @Panda-Beard, my guess is that your issue relates to SSL incompatibility.
Please open a new issue and upload images of the browser's console to let us look for errors and alerts related to GoDice.
When doing so, let me know whether you are using SSL or not.

**Comment by Panda-Beard** [comment]
Thanks @AKparticula 
I've opened one here: https://github.com/ParticulaCode/FoundryVTT-GoDice/issues/12
