### ISSUE TITLE
Dice configuration button is not visible

### ISSUE THREAD

**Issue by elsarfhem** [ParticulaCode/FoundryVTT-GoDice#21]
I cannot set the dice provider 
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/31951511/274d4305-30d5-4f45-b076-960adb9ab782)
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/31951511/4c9c7e9a-0db7-4d45-9742-b1ce171e63ef)
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/31951511/ee1b54ed-b102-40ea-9759-f38e2045e271)

**Comment by coffiarts** [comment]
I was having the same trouble. Then I found the missing config in the module settings instead. Looks like it has been moved there, without anyone telling us (or I just missed it)?
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/39616483/9f5b2d87-4683-4d9e-bcb7-7adaacb84237)
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/39616483/402bc136-0c56-4ede-9b87-a16aaac811a2)
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/39616483/40cb7666-176e-4287-af56-386b1f078e21)

**Comment by elsarfhem** [comment]
> I was having the same trouble. Then I found the missing config in the module settings instead. Looks like it has been moved there, without anyone telling us (or I just missed it)? ![image](https://private-user-images.githubusercontent.com/39616483/331864695-9f5b2d87-4683-4d9e-bcb7-7adaacb84237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTk5OTksIm5iZiI6MTcxNjExOTY5OSwicGF0aCI6Ii8zOTYxNjQ4My8zMzE4NjQ2OTUtOWY1YjJkODctNDY4My00ZDllLWJjYjctN2FkYWFjYjg0MjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDExNTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNTdkZWMyNmMzZTAxZjI2ZmIxYmM4MDlkMzVjNTJlNjY4NmJjZTY1ZWI1N2QyYmY5MzcyODFmMWVjZjlkNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w4erkGgSImTj0JMVCsWYuUpP2tkgFk2GsWJvzFKro-I) ![image](https://private-user-images.githubusercontent.com/39616483/331864752-402bc136-0c56-4ede-9b87-a16aaac811a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTk5OTksIm5iZiI6MTcxNjExOTY5OSwicGF0aCI6Ii8zOTYxNjQ4My8zMzE4NjQ3NTItNDAyYmMxMzYtMGM1Ni00ZWRlLTliODctYTE2YWFhYzgxMWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDExNTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYTgwY2Q0YWI4NjAyMGIyNWVhMjY3N2M0ZDU4OWE5NWU0NTM1ZjRjOTEzMzI1ZjEyZmE1ZTY0MWU1YWM0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bqj-xtY-JwsnN0fe3wFo2AM0TN0zoxHLwiD6CBGWUbE) ![image](https://private-user-images.githubusercontent.com/39616483/331864788-40cb7666-176e-4287-af56-386b1f078e21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTk5OTksIm5iZiI6MTcxNjExOTY5OSwicGF0aCI6Ii8zOTYxNjQ4My8zMzE4NjQ3ODgtNDBjYjc2NjYtMTc2ZS00Mjg3LWFmNTYtMzg2YjFmMDc4ZTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDExNTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYjY2YmJhMjdjOGUyN2IyYjZlNjU0YmRkYjkzNGViZmMzYThiNTUzN2NjN2UzZDliZjA4NzliNWJhNDY0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yNHadZQUCwpfLDjnjTTjydBZ2Z-xfcVyXLXzEGGeQAo)
Thanks
