### ISSUE TITLE
TypeError: undefined. Cannot read properties of undefined (reading 'connection')

### ISSUE THREAD

**Issue by myzar472** [ParticulaCode/FoundryVTT-GoDice#3]
Running the latest V11 FoundryVTT build 302 with a set of GoDice. An error is thrown in developer console running Chromium. The GoDice Companion prompt window appears fine, but no dice results appear.

The error is as follows on a brand new world with no modules except Unfulfilled Rolls and GoDice.
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/9061508/9efa57e5-3de9-435d-b6c9-45931d01ae8f)

```
TypeError: An error occurred while rendering GodiceResolver 49. Cannot read properties of undefined (reading 'connection')
    at GodiceResolver.activateListeners (godice-resolver.js:93:30)
    at GodiceResolver._render (foundry.js:5800:10)
    at async GodiceResolver._render (foundry.js:6488:5)
onError @ foundry.js:753
```
![image](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/9061508/acd62b0b-22bf-4e47-bb21-98035d59268c)
---
My phone is running Android and showing a websocket below (ws://192.168.1.147:8596), and laptop is on OSX running on WiFi on the same network as the phone. The phone is able to communicate with the dice.

**Comment by myzar472** [comment]
This issue is SSL related.

dice-connection.mjs:22 Mixed Content: The page at '***/foundry/game' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.147:8596/FoundryGDVTT'. This request has been blocked; this endpoint must be available over WSS.

**Comment by Anchor8900** [comment]
Try going to the Page Setting under the pad lock on the address bar and change Insecure Content to ALLOW. Cleared that error for me...

**Comment by AKparticula** [comment]
Thanks @myzar472 !
We are already working on enabling WSS through the GoDice app, and hope to provide it as soon as it'll work for us.

**Comment by AKparticula** [comment]
Closing this issue as this is related to the SSL issue. We are working on an app update to allow SSL. Stay tuned.
