### ISSUE TITLE
Showing no Interface/Chat Entry?

### ISSUE THREAD

**Issue by Hijah82** [ParticulaCode/FoundryVTT-GoDice#4]
I have a issue with the GoDice App (FoundryVTT v.11). When i start a diceroll request, the GoDice Window appears, but after the rolls itself the Chat shows a "!" as message reminder, but no Roll is shown in the Chat. Some other Game Worlds didnt react correct on a Roll Request, and show no GoDive Roll Interface on request out of the character sheet. Can you help me in finding the problem with this? Greetings.
![Screenshot 2023-06-22 160304](https://github.com/ParticulaCode/FoundryVTT-GoDice/assets/137417695/61e42a72-414f-4678-a7dc-b4afe4a2b302)

**Comment by AKparticula** [comment]
The issue was solved by an update to the unfulfilled rolles
