### ISSUE TITLE
No "Open Dice Configuration" under Game settings. Foundry VTT

### ISSUE THREAD

**Issue by dolonite** [ParticulaCode/FoundryVTT-GoDice#8]
No "Open Dice Configuration" under Game settings. Foundry VTT version 10 291 D&D 5E Version 2.2.1

**Comment by dolonite** [comment]
Ah yes found it. Not sure if you can help with the next issue but the app
on my iphone see the roll from the dice but the ws:// url is wrong its
coming up as 192.0.012:xxxx but my home LAN is 192.192.1.x

**Comment by AKparticula** [comment]
@dolonite I am closing this issue, 
About the IP, this is interesting - try turning mobile data off on your phone and restart the godice app.

**Comment by dolonite** [comment]
Just to let you know if i turn off cellular data, where the IP is supposed
to show up is empty.

**Comment by AKparticula** [comment]
Then you are not connected to your home wifi probably.

Feel free to contact me in discord if needed @ Katz Amit#5329
